/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from 'kysely';

export type Generated<T> =
  T extends ColumnType<infer S, infer I, infer U>
    ? ColumnType<S, I | undefined, U>
    : ColumnType<T, T | undefined, T>;

export type Numeric = ColumnType<string, number | string, number | string>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface Cliente {
  comentarios: string | null;
  created_at: Generated<Timestamp>;
  deleted_at: Timestamp | null;
  domicilio: string;
  encargado: string | null;
  factura: Generated<boolean>;
  id: Generated<string>;
  lat: Numeric | null;
  lista_precio_id: string;
  lng: Numeric | null;
  nombre: string;
  pct_comision: Numeric | null;
  plazo_credito_dias: number | null;
  promocion: Generated<string>;
  sucursal_id: string;
  telefono: string;
  tipo: string;
  tipo_negocio_id: string | null;
  updated_at: Generated<Timestamp>;
}

export interface ClientePrecio {
  cliente_id: string;
  created_at: Generated<Timestamp>;
  deleted_at: Timestamp | null;
  id: Generated<string>;
  precio: Numeric;
  presentacion_id: string;
  updated_at: Generated<Timestamp>;
  vigente_desde: Timestamp;
}

export interface ClientePromocionProducto {
  cliente_id: string;
  created_at: Generated<Timestamp>;
  deleted_at: Timestamp | null;
  id: Generated<string>;
  producto_id: string;
  updated_at: Generated<Timestamp>;
}

export interface CobranzaAbono {
  created_at: Generated<Timestamp>;
  deleted_at: Timestamp | null;
  fecha_pago: Timestamp;
  id: Generated<string>;
  metodo_pago: string;
  monto: Numeric;
  saldo_pendiente: Numeric;
  tipo: string;
  updated_at: Generated<Timestamp>;
  vendedor_id: string;
  venta_nota_id: string;
}

export interface ListaPrecio {
  created_at: Generated<Timestamp>;
  deleted_at: Timestamp | null;
  id: Generated<string>;
  nombre: string;
  updated_at: Generated<Timestamp>;
}

export interface Perfil {
  created_at: Generated<Timestamp>;
  deleted_at: Timestamp | null;
  id: Generated<string>;
  nombre: string;
  updated_at: Generated<Timestamp>;
}

export interface PerfilPermiso {
  created_at: Generated<Timestamp>;
  deleted_at: Timestamp | null;
  id: Generated<string>;
  perfil_id: string;
  permiso_id: string;
  updated_at: Generated<Timestamp>;
}

export interface Permiso {
  clave: string;
  created_at: Generated<Timestamp>;
  deleted_at: Timestamp | null;
  descripcion: string | null;
  grupo: string;
  id: Generated<string>;
  updated_at: Generated<Timestamp>;
}

export interface Precio {
  created_at: Generated<Timestamp>;
  deleted_at: Timestamp | null;
  id: Generated<string>;
  lista_precio_id: string;
  precio: Numeric;
  presentacion_id: string;
  sucursal_id: string;
  updated_at: Generated<Timestamp>;
  vigente_desde: Timestamp;
}

export interface Presentacion {
  created_at: Generated<Timestamp>;
  deleted_at: Timestamp | null;
  id: Generated<string>;
  producto_id: string;
  updated_at: Generated<Timestamp>;
  volumen: string;
}

export interface Producto {
  activo: Generated<boolean>;
  created_at: Generated<Timestamp>;
  deleted_at: Timestamp | null;
  id: Generated<string>;
  nombre: string;
  updated_at: Generated<Timestamp>;
}

export interface Ruta {
  cliente_id: string;
  created_at: Generated<Timestamp>;
  deleted_at: Timestamp | null;
  fecha: Timestamp;
  id: Generated<string>;
  orden: number;
  tipo: string;
  updated_at: Generated<Timestamp>;
  vendedor_id: string;
}

export interface Sucursal {
  activa: Generated<boolean>;
  codigo: string;
  created_at: Generated<Timestamp>;
  deleted_at: Timestamp | null;
  id: Generated<string>;
  nombre: string;
  updated_at: Generated<Timestamp>;
}

export interface TipoNegocio {
  created_at: Generated<Timestamp>;
  deleted_at: Timestamp | null;
  id: Generated<string>;
  nombre: string;
  updated_at: Generated<Timestamp>;
}

export interface Usuario {
  created_at: Generated<Timestamp>;
  deleted_at: Timestamp | null;
  id: Generated<string>;
  login: string;
  nombre: string;
  password_hash: string;
  perfil_id: string;
  sucursal_id: string | null;
  updated_at: Generated<Timestamp>;
}

export interface UsuarioPermiso {
  created_at: Generated<Timestamp>;
  deleted_at: Timestamp | null;
  habilitado: boolean;
  id: Generated<string>;
  permiso_id: string;
  updated_at: Generated<Timestamp>;
  usuario_id: string;
}

export interface Vehiculo {
  activo: Generated<boolean>;
  created_at: Generated<Timestamp>;
  deleted_at: Timestamp | null;
  id: Generated<string>;
  km_inicial: Numeric | null;
  nombre: string;
  sucursal_id: string;
  updated_at: Generated<Timestamp>;
}

export interface Vendedor {
  activo: Generated<boolean>;
  created_at: Generated<Timestamp>;
  deleted_at: Timestamp | null;
  id: Generated<string>;
  login: string;
  nombre: string;
  password_hash: string;
  sucursal_id: string;
  updated_at: Generated<Timestamp>;
}

export interface VentaNota {
  cliente_id: string;
  contado_credito: string;
  created_at: Generated<Timestamp>;
  deleted_at: Timestamp | null;
  factura: string | null;
  fecha: Timestamp;
  folio: string;
  id: Generated<string>;
  mes: number;
  monto_total: Generated<Numeric>;
  num_nota: string;
  semana: number;
  status: string;
  sucursal_id: string;
  updated_at: Generated<Timestamp>;
  vendedor_id: string;
}

export interface VentaNotaDetalle {
  cantidad: number;
  cantidad_promocion: Generated<number>;
  created_at: Generated<Timestamp>;
  deleted_at: Timestamp | null;
  id: Generated<string>;
  precio: Numeric;
  presentacion_id: string;
  updated_at: Generated<Timestamp>;
  venta_nota_id: string;
}

export interface DB {
  cliente: Cliente;
  cliente_precio: ClientePrecio;
  cliente_promocion_producto: ClientePromocionProducto;
  cobranza_abono: CobranzaAbono;
  lista_precio: ListaPrecio;
  perfil: Perfil;
  perfil_permiso: PerfilPermiso;
  permiso: Permiso;
  precio: Precio;
  presentacion: Presentacion;
  producto: Producto;
  ruta: Ruta;
  sucursal: Sucursal;
  tipo_negocio: TipoNegocio;
  usuario: Usuario;
  usuario_permiso: UsuarioPermiso;
  vehiculo: Vehiculo;
  vendedor: Vendedor;
  venta_nota: VentaNota;
  venta_nota_detalle: VentaNotaDetalle;
}
